FROM sonarqube:24.12.0.100206-community

COPY --chown=sonarqube:sonarqube plugins/* /opt/sonarqube/extensions/plugins/
COPY --chown=sonarqube:sonarqube sonar.properties /opt/sonarqube/conf/sonar.properties